# Generated by Django 4.2.4 on 2023-08-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='total',
            new_name='total_price',
        ),
    ]
